print("Olá, mundo")
print("O Carlos cheira mal!")
print("O Carlos é bem mais novo do que eu e já tem o futuro mais brilhante que a pele do yoongi.")
print("Todos as sextas feiras, na aula do Carlos eu estou famintaaaaaaaa!")
print("O Carlos é surdo!")
print("Espero que aprender Python me traga dinheiro mesmo eu não querendo me especializar em TI ><")
print("Tem só mais uma semana para o recesso e eu já não aguento mais esperar!")
print("Gostaria de merendar")
print("Posso ir embora?")
print("Tchau!")